name: Test Suite

on:
  push:
    branches: [master]
  pull_request:
    branches:
      - master
      - feature/*
      - bugfix/*
      - refactor/*
      - chore/*

jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/labeler@v3
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"

  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version:
          - v0.7.0
          - nightly
    steps:
      - uses: actions/checkout@v2
      - name: Install Plenary
        uses: actions/checkout@v2
        with:
          repository: nvim-lua/plenary.nvim
          path: plenary.nvim
      - name: Install Neovim
        uses: rhysd/action-setup-vim@v1
        id: neovim
        with:
          neovim: true
          version: ${{ matrix.version }}
      - name: Run tests
        run: make test

  luacheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: NTBBloodbath/selene-action@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --display-style=quiet .
